site_name: TraitBlender Documentation
site_description: Museum-style images for morphological datasets.
site_url: https://imageomics.github.io/TraitBlender/

repo_name: Imageomics/TraitBlender
repo_url: https://github.com/Imageomics/TraitBlender

theme:
  name: material
  palette:
    # Palette toggle for dark mode (default)
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.copy
    - toc.follow
    - navigation.indexes

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Blender Settings: getting-started/blender-optimization.md
    - Installation: getting-started/installation.md
    - Quick Start (GUI): getting-started/quick-start.md
  - User Documentation:
    - Overview: documentation.md
    - API Reference:
      - Operators and Properties: api/scene-assets.md
    - Configuration:
      - Configuration Files: configuration/config-files.md
  - Morphospaces:
    - Overview: morphospaces/overview.md
    - Shell (Default): morphospaces/shell.md
    - Circle Grid: morphospaces/circle-grid.md
    - ATLAS: morphospaces/atlas.md
  - Tutorials: tutorials.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Imageomics/TraitBlender
    - icon: fontawesome/solid/envelope
      link: mailto:calebcharpentier00@gmail.com

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3.2.2/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2025 Caleb Charpentier 
